import React, { useEffect, useState } from 'react';
import { Activity, ArrowRight, BadgeCheck, Database, ExternalLink, Globe2, Radar, Search, ShieldCheck, Sparkles, TrendingUp, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import HomeInstitutionalFooter from '@/components/home/HomeInstitutionalFooter';
import NewTokenRadar from '@/components/market/NewTokenRadar';
import LiveBlockFlow3D from '@/components/home/LiveBlockFlow3D';
import CommandCenterHeroVisual from '@/components/home/CommandCenterHeroVisual';

const Card=({icon:Icon,label,value='UNAVAILABLE',note})=><div className="rounded-2xl border border-sky-400/15 bg-[#07111f]/80 p-4 backdrop-blur-xl"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[.14em] text-slate-400">{label}</span><Icon className="h-4 w-4 text-sky-300"/></div><div className="mt-3 text-xl font-black text-white">{value}</div>{note&&<div className="mt-1 text-[10px] text-slate-500">{note}</div>}</div>;

const verifiedNumber=(v)=>v !== null && v !== undefined && v !== '' && Number.isFinite(Number(v)) ? Number(v) : null;
const fmtUsd=(v)=>Number.isFinite(v)?(v>=1e12?`${(v/1e12).toFixed(2)}T`:v>=1e9?`${(v/1e9).toFixed(2)}B`:`${v.toLocaleString('en-US',{maximumFractionDigits:0})}`):'UNAVAILABLE';
const fmtPct=(v)=>Number.isFinite(v)?`${v.toFixed(1)}%`:'UNAVAILABLE';
const fmtNum=(v)=>Number.isFinite(v)?v.toLocaleString('en-US'):'UNAVAILABLE';

export default function HomeV3(){
const [market,setMarket]=useState(null);
const [activeChains,setActiveChains]=useState(null);
const [zvq,setZvq]=useState(null);
const [pulse,setPulse]=useState(null);
const [query,setQuery]=useState('');
const submitSearch=(event)=>{event.preventDefault();const value=query.trim();if(!value)return;const evm=/^0x[a-fA-F0-9]{40}$/.test(value);const tx=/^0x[a-fA-F0-9]{64}$/.test(value);const block=/^\d+$/.test(value);if(tx)window.location.assign(`https://explorer.kriptoaman.com/tx/${value}`);else if(evm)window.location.assign(`/asset-passport/${value}`);else if(block)window.location.assign(`https://explorer.kriptoaman.com/block/${value}`);else window.location.assign(`/Market?search=${encodeURIComponent(value)}`);};
useEffect(()=>{let live=true; const load=async()=>{try{const [m,n,z,p]=await Promise.allSettled([fetch('/api/market-overview',{headers:{Accept:'application/json'},cache:'no-store'}),fetch('/api/network-health',{headers:{Accept:'application/json'},cache:'no-store'}),fetch('/api/kam/network-status',{headers:{Accept:'application/json'},cache:'no-store'}),fetch('/api/zvq-token-intelligence',{headers:{Accept:'application/json'},cache:'no-store'})]);if(!live)return;if(m.status==='fulfilled'&&m.value.ok){const p=await m.value.json();if(live&&p?.status==='available')setMarket(p);}if(n.status==='fulfilled'&&n.value.ok){const p=await n.value.json();const online=Number(p?.summary?.online);if(live&&Number.isFinite(online))setActiveChains(online);}if(z.status==='fulfilled'&&z.value.ok){const p=await z.value.json();if(live)setZvq(p?.live===true&&p?.verified===true?p:null);}if(p.status==='fulfilled'&&p.value.ok){const q=await p.value.json();if(live&&q?.status==='live'&&Number(q?.chainId)===22028)setPulse(q);}}catch{/* Keep verified-data placeholders on failure. */}};load();const t=setInterval(load,60000);return()=>{live=false;clearInterval(t)}} ,[]);
return <div className="ka-home-v3 ka-bg min-h-screen text-white">
<style>{`.ka-orb{background:radial-gradient(circle at 38% 34%,rgba(56,189,248,.5),rgba(30,64,175,.16) 35%,rgba(2,6,23,.08) 64%),linear-gradient(135deg,rgba(14,165,233,.18),rgba(245,158,11,.08));box-shadow:inset 0 0 80px rgba(56,189,248,.2),0 0 90px rgba(14,165,233,.16)}.ka-grid3d{background-image:linear-gradient(rgba(56,189,248,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(56,189,248,.08) 1px,transparent 1px);background-size:32px 32px;transform:perspective(600px) rotateX(64deg);transform-origin:center bottom}@media(max-width:1023px){body:has(.ka-home-v3) .ka-global-shell>div:last-child{height:calc(5.5rem + env(safe-area-inset-bottom,0px))}}`}</style>
<div className="mx-auto max-w-7xl px-4 pt-4 sm:px-6 lg:px-8">
<section className="relative overflow-hidden rounded-[32px] border border-sky-400/20 bg-[#030914] shadow-[0_34px_100px_-48px_rgba(14,165,233,.8)]"><div className="ka-grid3d pointer-events-none absolute -bottom-24 left-0 right-0 h-80 opacity-70"/><div className="relative grid min-h-[390px] gap-5 p-5 sm:min-h-[470px] sm:gap-8 sm:p-9 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
<div className="z-10"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-black tracking-[.14em] text-emerald-300"><Activity className="h-3.5 w-3.5"/> LIVE PRODUCTION INTELLIGENCE</div><h1 className="mt-4 text-[2.15rem] font-black leading-[.96] tracking-[-.055em] sm:mt-5 sm:text-6xl">KRIPTOAMAN<br/><span className="text-sky-300">CRYPTO COMMAND CENTER</span></h1><p className="mt-3 max-w-xl text-xs leading-5 text-slate-300 sm:mt-4 sm:text-sm sm:leading-6">Live market context, ZEVARYQ on-chain evidence, network operations, asset discovery, and verification in one production workspace. Every critical state stays traceable to its source.</p><form onSubmit={submitSearch} className="mt-4 flex max-w-2xl items-center gap-2 rounded-2xl sm:mt-6 border border-sky-400/20 bg-[#07111f]/90 p-2 shadow-[0_18px_50px_-28px_rgba(56,189,248,.65)]"><Search className="ml-2 h-5 w-5 shrink-0 text-sky-300"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Universal intelligence search" placeholder="Token / Contract / Wallet / Transaction / Block" className="min-w-0 flex-1 bg-transparent px-2 py-3 text-sm text-white outline-none placeholder:text-slate-500"/><button type="submit" className="min-h-11 rounded-xl bg-sky-500 px-4 text-xs font-black text-slate-950">SEARCH</button></form><div className="mt-3 flex flex-wrap gap-2 sm:mt-4 sm:gap-3"><Link to="/Market" className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-blue-600 px-5 text-sm font-extrabold">Explore Markets <ArrowRight className="h-4 w-4"/></Link><Link to="/IntelligenceHub" className="inline-flex min-h-12 items-center gap-2 rounded-2xl border border-sky-400/20 bg-sky-400/10 px-5 text-sm font-bold">Open Intelligence</Link><a href="https://explorer.kriptoaman.com" className="inline-flex min-h-12 items-center gap-2 rounded-2xl border border-amber-400/25 bg-amber-400/10 px-5 text-sm font-bold text-amber-200">ZEVARYQ Explorer</a></div></div>
<CommandCenterHeroVisual zvq={zvq} market={market} activeChains={activeChains} pulse={pulse}/></div></section>\n<LiveBlockFlow3D/>
<section className="mt-5"><div className="mb-3 flex items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-slate-500">GLOBAL MARKET PULSE</p><h2 className="text-lg font-black">Market Context</h2></div><Link to="/Market" className="text-[10px] font-black text-sky-300">FULL MARKET →</Link></div><div className="grid grid-cols-2 gap-2 sm:gap-3 md:grid-cols-3 lg:grid-cols-6"><Card icon={TrendingUp} label="Market Cap" value={fmtUsd(verifiedNumber(market?.marketCap))} note="KriptoAman market API"/><Card icon={Activity} label="24h Volume" value={fmtUsd(verifiedNumber(market?.volume24h))} note="KriptoAman market API"/><Card icon={Database} label="BTC Dominance" value={fmtPct(verifiedNumber(market?.btcDominance))} note="KriptoAman market API"/><Card icon={Sparkles} label="Market Sentiment" value={verifiedNumber(market?.fearGreed)!=null?`${verifiedNumber(market.fearGreed)} · ${market?.fearGreedLabel||'Index'}`:'UNAVAILABLE'} note="Fear & Greed via KriptoAman API"/><Card icon={Radar} label="Tracked Assets" value={fmtNum(verifiedNumber(market?.activeCryptocurrencies))} note="Active cryptocurrencies upstream"/><Card icon={Globe2} label="Active Chains" value={fmtNum(verifiedNumber(activeChains))} note="Successful current network probes"/></div></section>
<section className="mt-5 rounded-[28px] border border-cyan-400/15 bg-[#050d17]/92 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-300">CHAIN PULSE · FIRST-PARTY EVIDENCE</p><h2 className="mt-1 text-xl font-black">What is happening on ZEVARYQ now?</h2></div><div className={`rounded-full border px-3 py-1.5 text-[9px] font-black uppercase tracking-[.12em] ${pulse?'border-emerald-400/20 bg-emerald-400/10 text-emerald-300':'border-white/10 bg-white/[.04] text-slate-400'}`}>{pulse?'LIVE EVIDENCE':'UNAVAILABLE'}</div></div>{pulse?<div className="mt-4 grid gap-2 md:grid-cols-2"><div className="rounded-2xl border border-sky-400/10 bg-sky-400/[.035] p-4"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.12em] text-sky-300"><Activity className="h-4 w-4"/> Chain Head</div><div className="mt-2 text-2xl font-black">#{Number(pulse?.head?.number).toLocaleString('en-US')}</div><p className="mt-1 text-[10px] text-slate-500">Observed through KriptoAman first-party intelligence · {pulse?.sourceMode||pulse?.provenance?.transport||'read-only source'}</p>{Number.isFinite(Number(pulse?.head?.number))&&<a href={`https://explorer.kriptoaman.com/block/${Number(pulse.head.number)}`} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[10px] font-black text-cyan-300">VERIFY BLOCK <ExternalLink className="h-3 w-3"/></a>}</div><div className="rounded-2xl border border-violet-400/10 bg-violet-400/[.035] p-4"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.12em] text-violet-300"><BadgeCheck className="h-4 w-4"/> Discovery Evidence</div><div className="mt-3 grid grid-cols-2 gap-2"><div><div className="text-xl font-black">{pulse?.radar?.contractCreationsObserved??'—'}</div><div className="text-[8px] uppercase tracking-[.12em] text-slate-500">Contracts observed</div></div><div><div className="text-xl font-black">{pulse?.radar?.tokenMetadataProven??'—'}</div><div className="text-[8px] uppercase tracking-[.12em] text-slate-500">Metadata proven</div></div></div><p className="mt-3 text-[10px] leading-5 text-slate-500">Contract creation is observation only. It is not a listing, liquidity proof, security audit, or endorsement.</p></div></div>:<div className="mt-4 rounded-2xl border border-white/[.06] bg-white/[.02] p-4 text-xs text-slate-500">No fresh first-party evidence is being presented. KriptoAman does not synthesize Chain Pulse events.</div>}</section>
<section className="mt-5 grid gap-4 lg:grid-cols-[1.45fr_.55fr]"><div className="overflow-hidden rounded-[26px] border border-sky-400/15 bg-[#050d17]/88 p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-sky-300">Emerging On-Chain Activity</p><h2 className="text-xl font-black">New Token Radar</h2></div><Radar className="h-6 w-6 text-sky-300"/></div><NewTokenRadar/></div><div className="space-y-4"><div className="rounded-[26px] border border-violet-400/15 bg-[#050d17]/88 p-5"><WalletCards className="h-6 w-6 text-violet-300"/><h2 className="mt-4 text-xl font-black">Asset Passport</h2><p className="mt-2 text-xs leading-5 text-slate-400">Contract identity, chain, liquidity and holder context, on-chain activity, and risk indicators only when source evidence is available.</p><Link to="/QoryVExDiscovery" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-violet-300">Inspect assets <ArrowRight className="h-3 w-3"/></Link></div><div className="rounded-[26px] border border-emerald-400/15 bg-[#050d17]/88 p-5"><ShieldCheck className="h-6 w-6 text-emerald-300"/><h2 className="mt-4 text-xl font-black">Trust & Transparency</h2><p className="mt-2 text-xs leading-5 text-slate-400">LIVE, DEGRADED and UNAVAILABLE states reflect evidence. Missing production data is never replaced with invented metrics.</p><Link to="/SystemStatus" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-emerald-300">System status <ArrowRight className="h-3 w-3"/></Link></div></div></section>
<section className="mt-5 rounded-[28px] border border-emerald-400/15 bg-[#050d17]/92 p-5"><div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-emerald-300">PROOF OF INTELLIGENCE</p><h2 className="mt-1 text-2xl font-black">Insight → Evidence → Blockchain</h2><p className="mt-3 text-xs leading-6 text-slate-400">KriptoAman separates observation from interpretation. Production evidence remains traceable to chain identity, block, transaction or contract when those fields are available.</p></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[['OBSERVATION','Direct first-party chain facts'],['CONTEXT','Related verified activity'],['INTERPRETATION','Derived analysis, explicitly labelled'],['EVIDENCE','Block · tx · contract · freshness']].map(([title,note])=><div key={title} className="rounded-2xl border border-white/[.06] bg-white/[.025] p-4"><div className="text-[10px] font-black tracking-[.12em] text-emerald-300">{title}</div><p className="mt-2 text-[10px] leading-5 text-slate-500">{note}</p></div>)}</div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-white/[.06] pt-4"><p className="text-[9px] leading-4 text-slate-500">UNAVAILABLE is never converted into zero, live, healthy, verified, or estimated.</p><Link to="/SystemStatus" className="inline-flex items-center gap-2 text-[10px] font-black text-emerald-300">VIEW SYSTEM EVIDENCE <ArrowRight className="h-3 w-3"/></Link></div></section>
<section className="mt-5 rounded-[28px] border border-violet-400/15 bg-[#050d17]/92 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-violet-300">MY INTELLIGENCE</p><h2 className="mt-1 text-2xl font-black">Your monitored market, without noise.</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-400">Open your watchlist, portfolio and alerts from one focused workspace. KriptoAman only surfaces values and signals returned by their production sources.</p></div><Link to="/Alerts" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-400/10 px-4 text-xs font-black text-violet-200">OPEN ALERTS <ArrowRight className="h-3 w-3"/></Link></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Link to="/Market" className="rounded-2xl border border-white/[.06] bg-white/[.025] p-4"><div className="text-[10px] font-black text-sky-300">DISCOVER</div><p className="mt-2 text-xs text-slate-400">Markets, movers and verified discovery.</p></Link><Link to="/PortfolioOverview" className="rounded-2xl border border-white/[.06] bg-white/[.025] p-4"><div className="text-[10px] font-black text-violet-300">PORTFOLIO</div><p className="mt-2 text-xs text-slate-400">Watch-only holdings and portfolio context.</p></Link><Link to="/IntelligenceHub" className="rounded-2xl border border-white/[.06] bg-white/[.025] p-4"><div className="text-[10px] font-black text-emerald-300">INTELLIGENCE</div><p className="mt-2 text-xs text-slate-400">Evidence, risk context and network intelligence.</p></Link></div></section>
</div><div className="mx-auto mt-5 max-w-7xl border-t border-sky-400/10 px-4 pb-1 pt-5 sm:px-6 sm:pb-2 lg:px-8"><HomeInstitutionalFooter/></div></div>}