import React, { useState, useEffect } from 'react';
import { Shield, TrendingUp, Lock, Globe, ArrowRight, BarChart3, Wallet, Eye, Menu, X, Activity, BookOpen } from 'lucide-react';

const FEATURES = [
  { icon: TrendingUp, title: 'Pemantauan Pasar', desc: 'Pantau data aset digital dan perubahan pasar dalam antarmuka yang ringkas dan mudah dipahami.' },
  { icon: Wallet, title: 'Wallet Monitoring', desc: 'Hubungkan alamat wallet untuk pemantauan. KriptoAman tidak meminta seed phrase atau private key.' },
  { icon: Shield, title: 'Security First', desc: 'Kontrol sesi, autentikasi, dan lapisan keamanan dirancang untuk pengalaman penggunaan yang lebih aman.' },
  { icon: BookOpen, title: 'Edukasi & Risiko', desc: 'Informasi dan konteks risiko membantu pengguna memahami aset digital sebelum mengambil keputusan.' },
  { icon: BarChart3, title: 'Analitik yang Jelas', desc: 'Informasi pasar disajikan dengan fokus pada keterbacaan, transparansi sumber, dan pengalaman mobile.' },
  { icon: Globe, title: 'Indonesia, Global Standard', desc: 'Bahasa Indonesia dan Inggris dengan pengalaman produk yang dirancang untuk berkembang secara global.' },
];

function LogoSVG({ size = 40 }) { return <img src="/kriptoaman-logo-primary.png" width={size} height={size} alt="KriptoAman" className="object-contain" />; }

function NavBar() {
  const [scrolled, setScrolled] = useState(false); const [mobileOpen, setMobileOpen] = useState(false);
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 40); window.addEventListener('scroll', fn); return () => window.removeEventListener('scroll', fn); }, []);
  const links = [{label:'Fitur',href:'#fitur'},{label:'Keamanan',href:'#trust'},{label:'Founder',href:'/Founder'},{label:'Status',href:'/SystemStatus'}];
  return <nav className={`fixed top-0 left-0 right-0 z-50 transition-all ${scrolled?'bg-[#060d1a]/95 backdrop-blur border-b border-sky-900/40':'bg-transparent'}`}><div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between gap-4"><a href="/" className="flex items-center gap-2.5"><LogoSVG size={34}/><span className="font-extrabold tracking-widest uppercase"><span>Kripto</span><span className="text-emerald-400">Aman</span></span></a><div className="hidden md:flex items-center gap-6">{links.map(l=><a key={l.href} href={l.href} className="text-slate-400 hover:text-white text-sm font-semibold">{l.label}</a>)}</div><div className="flex items-center gap-2"><a href="/Home" className="px-4 py-2 bg-sky-500 text-white text-sm font-bold rounded-xl hover:bg-sky-400">Buka Aplikasi</a><button aria-label="Menu" className="md:hidden p-2 text-slate-300" onClick={()=>setMobileOpen(v=>!v)}>{mobileOpen?<X className="w-5 h-5"/>:<Menu className="w-5 h-5"/>}</button></div></div>{mobileOpen&&<div className="md:hidden bg-[#060d1a]/98 border-t border-slate-800 px-4 py-4 flex flex-col gap-4">{links.map(l=><a key={l.href} href={l.href} onClick={()=>setMobileOpen(false)} className="text-slate-300 font-semibold text-sm">{l.label}</a>)}</div>}</nav>;
}

export default function LandingPage() { return <div className="min-h-screen bg-[#060d1a] text-white overflow-x-hidden"><NavBar/>
<section className="relative min-h-[88vh] flex items-center justify-center px-4 pt-24 pb-14 overflow-hidden"><div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[620px] h-[620px] bg-sky-500/10 rounded-full blur-3xl"/><div className="relative z-10 max-w-4xl mx-auto text-center flex flex-col items-center"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-emerald-500/25 bg-emerald-500/8 text-emerald-300 text-xs font-bold mb-7"><Activity className="w-4 h-4"/> Informasi · Pemantauan · Edukasi Aset Digital</div><div className="mb-6"><LogoSVG size={150}/></div><h1 className="text-4xl sm:text-6xl font-black leading-tight tracking-tight">Memahami kripto dengan<br/><span className="bg-gradient-to-r from-sky-300 via-cyan-300 to-emerald-300 bg-clip-text text-transparent">lebih aman dan transparan.</span></h1><p className="text-slate-400 text-base sm:text-lg max-w-2xl mt-6 leading-relaxed">KriptoAman membantu pengguna memantau pasar, memahami aktivitas wallet, mempelajari risiko aset digital, dan melihat informasi blockchain dalam pengalaman yang sederhana dan modern.</p><div className="flex flex-col sm:flex-row gap-3 mt-9"><a href="/Home" className="px-7 py-3.5 bg-sky-500 hover:bg-sky-400 rounded-2xl font-bold flex items-center justify-center gap-2">Buka KriptoAman <ArrowRight className="w-4 h-4"/></a><a href="/SystemStatus" className="px-7 py-3.5 border border-slate-700 bg-slate-900/70 rounded-2xl font-bold flex items-center justify-center gap-2"><Activity className="w-4 h-4 text-emerald-300"/> System Status</a></div><p className="text-[11px] text-slate-500 mt-5">KriptoAman adalah platform informasi dan pemantauan. Informasi yang ditampilkan bukan nasihat keuangan.</p></div></section>
<section id="fitur" className="max-w-6xl mx-auto px-4 py-20"><p className="text-sky-300 text-xs font-bold uppercase tracking-[.2em]">Core Experience</p><h2 className="text-3xl sm:text-4xl font-black mt-3 max-w-2xl">Fokus pada hal yang benar-benar dibutuhkan pengguna.</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-9">{FEATURES.map(({icon:Icon,title,desc})=><div key={title} className="rounded-3xl border border-slate-800 bg-slate-900/55 p-6"><div className="w-11 h-11 rounded-2xl bg-sky-500/10 border border-sky-500/20 flex items-center justify-center"><Icon className="w-5 h-5 text-sky-300"/></div><h3 className="font-bold text-lg mt-5">{title}</h3><p className="text-sm text-slate-400 leading-relaxed mt-2">{desc}</p></div>)}</div></section>
<section id="trust" className="border-y border-slate-800/70 bg-slate-950/35"><div className="max-w-6xl mx-auto px-4 py-20 grid lg:grid-cols-2 gap-8 items-center"><div><p className="text-emerald-300 text-xs font-bold uppercase tracking-[.2em]">Trust by design</p><h2 className="text-3xl sm:text-4xl font-black mt-3">Kepercayaan dibangun dengan transparansi.</h2><p className="text-slate-400 mt-5 leading-relaxed">Sumber pihak ketiga dapat mengalami gangguan, data pasar dapat berubah, dan pengguna tetap memegang kendali atas wallet mereka.</p><div className="mt-6 flex flex-wrap gap-4"><a href="/SystemStatus" className="text-sky-300 font-semibold">Status sistem →</a><a href="/SecurityCenter" className="text-sky-300 font-semibold">Security Center →</a><a href="/Disclaimer" className="text-sky-300 font-semibold">Disclaimer →</a></div></div><div className="rounded-3xl border border-emerald-500/20 bg-emerald-500/5 p-7"><Lock className="w-8 h-8 text-emerald-300"/><h3 className="font-bold text-xl mt-5">Wallet safety</h3><p className="text-slate-400 text-sm leading-relaxed mt-3">KriptoAman tidak meminta seed phrase atau private key. Pengguna harus selalu memverifikasi tindakan pada wallet mereka sendiri.</p><div className="mt-5 flex items-center gap-2 text-xs text-emerald-300 font-bold"><Eye className="w-4 h-4"/> Transparent by default</div></div></div></section>
<section className="max-w-6xl mx-auto px-4 py-20"><div className="rounded-[2rem] border border-sky-500/20 bg-gradient-to-br from-slate-900 to-[#071525] p-6 sm:p-9 grid md:grid-cols-[140px_1fr] gap-6 items-center"><img src="/images/raden-abdul-rahman-founder.jpg" alt="Raden Abdul Rahman, M.Sc. — Founder & CEO KriptoAman" className="w-32 h-32 rounded-3xl object-cover border border-sky-500/20"/><div><p className="text-sky-300 text-xs font-bold uppercase tracking-[.18em]">Founder & Leadership</p><h2 className="text-2xl font-black mt-2">Raden Abdul Rahman, M.Sc.</h2><p className="text-slate-400 mt-3 leading-relaxed max-w-3xl">Memimpin KriptoAman dengan fokus pada keamanan informasi, transparansi data, edukasi aset digital, dan pengalaman pengguna yang profesional.</p><a href="/Founder" className="inline-flex items-center gap-2 text-sky-300 font-bold mt-4">Profil Founder <ArrowRight className="w-4 h-4"/></a></div></div></section>
<footer className="border-t border-slate-800"><div className="max-w-6xl mx-auto px-4 py-9 flex flex-col md:flex-row justify-between gap-5 text-sm text-slate-500"><div className="flex items-center gap-2"><LogoSVG size={28}/><span>© 2026 PT KRIPTO AMAN INDONESIA</span></div><div className="flex flex-wrap gap-4"><a href="/PrivacyPolicy">Privacy</a><a href="/TermsOfService">Terms</a><a href="/Disclaimer">Disclaimer</a><a href="/Support">Support</a><a href="/SystemStatus">Status</a></div></div></footer></div>; }
